name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Étape 3 : Cache Maven Dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Étape 4 : Construire le Projet avec Maven
      - name: Build with Maven
        run: mvn clean install

      # Étape 5 : Exécuter les Tests avec Maven Surefire
      - name: Run tests
        run: mvn test

      # Étape 6 : Générer le Rapport de Couverture avec JaCoCo
      - name: Generate JaCoCo Report
        run: mvn jacoco:report

      # Étape 7 : Upload du Rapport JaCoCo sur Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
